### ISSUE TITLE
✨ [Feature]  검색창 추천 API 구현

### ISSUE THREAD

**Issue by donghyun1998** [mejaiKR/Backend#14]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- query에 nickname : string 요소를 받아서 해당 string으로 시작하는 유저 정보 배열로 리턴
- 없으면 빈 배열 리턴

## 📝 기능 상세 내용

- 구현 관련 상세 내용 작성

## ✅ TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
