### ISSUE TITLE
✨ [Feature] 새로운 아이콘 업데이트

### ISSUE THREAD

**Issue by donghyun1998** [mejaiKR/Backend#15]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 새로운 아이콘이 추가되어서 이미지가 깨집니다
- 업데이트 부탁드립니다

## 📝 기능 상세 내용

- 구현 관련 상세 내용 작성

## ✅ TODO

- [x] 아이콘 업데이트 자동화 필요하다고 생각합니다.

**Comment by kimchijinju** [comment]
자동화 완료하여 이슈 닫겠습니다
