### ISSUE TITLE
✨ [Feature] 웹훅 테스트

### ISSUE THREAD

**Issue by Hawardshin** [mejaiKR/Backend#21]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 웹훅 동작확인

## 📝 기능 상세 내용

- 구현 관련 상세 내용 작성

## ✅ TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
